---

  - name: Distribution
    ansible.builtin.debug: 
      msg: "{{ ansible_distribution }}"


  - name: Distribution version
    ansible.builtin.debug: 
      msg: "{{ ansible_distribution_version}}"

  - name: Distribution major version
    ansible.builtin.debug: 
      msg: "{{ ansible_distribution_major_version }}"

  - name: Install rpmfusion free
    ansible.builtin.package:
      name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm" 
      state: present
